before_install:
  - chmod +x ./ci/install-deps.sh
  - chmod +x ./ci/build.sh
language: node_js
node_js:
- "lts/*"
install: ./ci/install-deps.sh
script: ./ci/build.sh
cache:
  directories:
    - node_modules
